[quote.epigraph, , 2 Cor. 1:12]
____
For our rejoicing is this, the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom,
but by the grace of God, we have conducted ourselves in the world.
____

== The Life of Abel Thomas

This may be fitly applied to the subject of this memoir; who,
having very little knowledge of literature, and being naturally of a shy,
diffident disposition,
associating in his youthful days but little with those from whose experience and judgment
he could have acquired such an understanding of men and things as is common,
was thereby deprived of those advantages which in more advanced
life might have been really beneficial to him.

He was the son of Jacob and Catharine Thomas, who lived in Merion, Philadelphia county.
His mother dying while he was an infant, his father married again,
and having a large family, his circumstances slender, and removing into a remote place,
where there was no school,
Abel was of course deprived of the benefit of an education sufficient
to qualify him for carrying on trade and business among men,
other than as a common day-labourer.

When about thirteen years old he became uneasy on account of his lack of school learning,
and with the scanty means which he could obtain in his father`'s house,
by diligent application in leisure hours, he attained the knowledge of letters,
so as to read,
and through the kind assistance of a neighbour was enabled to write so as to be understood,
though very deficient in spelling.

The meeting being about ten miles distant, although he had a desire to attend it,
yet through the poverty of the family, and lack of suitable convenience for that purpose,
it does not appear that he ever was at a place of worship until he was about fifteen.
Then with his father`'s leave, his elder brother and himself went to the meetinghouse;
where, seeing a number of people sitting together in silence,
the scene to him was not only novel,
but his mind not being acquainted with the nature and awfulness of divine worship,
and the requisite preparation of heart to come to a true knowledge of it,
could not readily comprehend why it should be thus,
or what should induce this quiet waiting and inward retirement to experience
a qualification for the performance of this solemn duty.
After some time, an elderly Friend, under the influence of the love of the Gospel,
stood up and spoke with such power and energy, as fully reached his state,
opened his understanding, and gave him to see and feel in some degree,
the efficacy of that grace and truth which came by Jesus Christ.
Speaking of this meeting he says, "`it was not the words that confirmed me,
but something of a flavour +++[+++savour]
that attended them, which I did evidently feel in my heart, saying, this is the way,
walk in it.`"

Submitting to this divine visitation,
he was drawn to labour fervently against the prevalence of his own corrupt will;
for although he had been preserved in a moral life,
or what is generally esteemed in the world an orderly regular conduct,
yet now through the illumination of Divine Light,
seeing that the heart of man is deceitful and desperately wicked,
he found the necessity of daily watching against the motions and temptations to evil,
that every thought and word might be brought to judgment,
and the very important work of regeneration might, through the Lord`'s goodness,
be gradually carried on,
to the subduing of those dispositions and inclinations
to which man in his fallen state is prone.
As he patiently, and with sincerity of soul,
waited under the ministration of condemnation, he was often drawn into retirement,
desiring that through the Holy Spirit he might find grace to help in time of need,
assuredly believing that without this,
he was not able to make straight steps to his feet,
or perform anything that would be acceptable in the divine sight.
And in thankful commemoration of the mercy and paternal regard of his heavenly Father,
manifested in drawing near to him in this the day of his many trials and besetraents,
he breaks forth in filial acknowledgment: "`I can say from all the powers of love in me,
blessing and honour be given to the Father of mercies through his dear Son Jesus Christ.`"

He continued working very hard on his father`'s farm,
and through the weight of his spirit and his watchful circumspect walking,
a reformation was wrought in the family, much harmony subsisted among them,
and great nearness of affectionate sympathy towards him in his various exercises prevailed.
Believing that retirement in this the infant state of his religious experience was needful,
he obtained liberty of his father to put up a little cabin,
where he might be more secluded from company, and here much of his time was spent,
when not engaged in secular concerns.
One night as he was walking alone with his mind gathered into a solemn calm,
he had a gentle intimation communicated to his spiritual ear,
that it would be right for him to leave his father`'s house,
and proceed in a northeasterly direction to such place as
it would be proper for him to reside in for some time.
As this was an unexpected opening, it brought considerable exercise upon him,
through the weight whereof, and his fervent desire to be rightly directed,
he became so reduced in his health and strength that
he could scarcely perform his usual daily labour.
He then opened the subject to his father,
mentioning his belief that he should have to leave him,
to live in another part of the country; his father replied,
it would be hard to part with him;
and under a feeling of the influence of true love raised in their hearts,
and which had increased and tenderly united them together, they both wept.

After some time, the family on due deliberation,
resigning him to pursue what he apprehended to be his duty,
he informed them that from the prospect presented to him,
it did not appear that it would be further than about sixty miles,
though he was entirely unacquainted with the country or the people where he should settle.
His brother through tender sympathy accompanying him,
they went on as far as Kingwood in New Jersey, where there was a settlement of Friends,
and a monthly meeting established.
To this meeting a certificate of removal was granted him, dated fourth month, 1757.
Here he engaged as a labourer on a farm with a person not professing with Friends.
His diligence in business, and his humble, inoffensive demeanour,
greatly attached the affection of his employer to him, and in his new abode,
he still found it needful to keep in patience and watchfulness under his religious exercises,
carefully attending the meetings of Friends.
It is believed that in this place his mouth was first
opened in the ministry of the gospel,
and in due time, with the concurrence of Friends,
he performed a religious visit to some of the meetings in New Jersey.

He stayed in this neighbourhood between four and five years,
married a member of Burlington meeting in 1761,
and lived some time among Friends near Mount Holly.
But his wife dying,
and believing it would be right for him to return to the vicinity of his father`'s residence,
he accordingly removed, and in a few years after married his second wife, Ellin Roberts,
of Uwchlan, in the year 1777.
While sitting at the table on the day of his marriage,
he expressed himself nearly as follows:--"`I feel a freedom to express my thoughts.
Marriages are commonly places of rejoicing; but when we look at what is to come,
we find but little room to rejoice in transitory things.

"`Notwithstanding I have been this day joined in marriage to one whom I do entirely love,
I know, so surely as we have been joined in marriage, so surely that hour will come,
when we must, by death be separated.
It is best for us, and for all,
to be industrious in gathering strength against that time to come,
so that the one of us that is first called home may
be prepared for so great and final a change,
and the survivor be fortified with strength, to endure, with resignation,
the bitter parting with so intimate a friend.

"`Under one consideration, my friends, my relatives,
I may this day rejoice,--in that I perceive what I have done has not offended Him,
whom I have loved more than my love who now sits on my right hand.
Surely, I am under the strongest obligations to worship and adore that immortal King,
who has been unto me as a shield and buckler, in my lonesome and afflicted pilgrimage.
Surely I may in safety rejoice in the Lord, the God of my salvation; and,
with all my might, ascribe unto Him the glory, and the praise of all,
who is worthy forever!`"

Some time after this he removed with his family and resided at Exeter, in Pennsylvania,
maintaining a good example in life and conduct,
and was diligent in the attendance of meetings for worship and discipline.
His labours in the exercise of the gift of gospel ministry committed to him,
were savoury and truly edifying, not in the words which man`'s wisdom teaches,
but in demonstration of the Spirit and of power;
and however singular and unpolished his general deportment might appear to some,
it was evident to his brethren,
that the primary care and bent of his mind was so to live as to
be in fellowship with the Father and his Son Jesus Christ.

On a retrospective view of his retired, abstemious life,
his general seclusion from the company of the youth with whom he was acquainted,
and the great change which a subjection to the cross of Christ effected,
he remarked that whenever he gave way to his natural inclination,
and sought to please the vain and airy minds of the youth in their folly, jesting, etc.,
though he said or did nothing that men in general would condemn,
yet the swift witness in his own breast would rise up against him,
bring him into judgment and condemnation,
and with much painful suffering under the purifying baptism of the Holy Spirit and fire,
he had to wait before he could again experience the lifting
up of the light of the Lord`'s countenance upon him,
and know a communion with him in spirit, that sets the soul at liberty,
and gives it a true taste of eternal salvation.

In a sense of the Lord`'s mercy and divine compassion to humble penitent sinners,
he breaks forth in pious exclamation,
"`Blessing and honour be forever given unto the Father of mercies
through his dear Son Jesus Christ--the Father and the Son are one:
God is a Spirit,
and in spirit he is to be known and conversed with by the children of men,
who endeavour to follow him according to the manifestation of his will,
without respect of persons.
And as he does know that we are in a miserable state without him,
not able to do anything without his help,
he makes the first offer of acquaintance with us,
and from the great love he has to his creature man,
speaks in the inward parts by his Son Jesus Christ, the Light of the world,
showing us the way to please him, and also points out the way to everlasting misery.
There is no sincere-hearted traveller that desires to follow the instructions
of that grace that teaches to deny ungodliness and the world`'s lusts,
to live soberly and watchful unto prayer,
that will be at a loss to know how to behave in his presence.
Our Lord said that a man must be born again,
otherwise he cannot see the kingdom of heaven.
As Christians we are bound to believe this,
and endeavouring to turn our attention heavenward more and more,
according to the manifestations of that grace or light,
which we are all graciously favoured with, by and through Jesus Christ,
who has bought us with a price, and that not without blood;
it is possible for us through obedience to obtain the kingdom.
We frequently feel that there is another usurping limited power,
which by subtle delusions works upon the natural passions of men,
in order to hinder them from laying up treasure in heaven:
thus we find there are two teachers or powers opposite to each other,
and he to whom we yield our members servants to obey, his servants we are.`"

In the year 1778,
after much close exercise from a prospect of religious duty which he opened to,
and was united with by, Exeter monthly meeting, of which he was a member,
he proceeded on a visit to some meetings in New Jersey,
and in part of the state of New York, having for his companion James Thomas,
a member of the same meeting.
As this was in the time of the Revolutionary War,
and the city of New York was then in possession of the British troops,
travelling in our country was rendered extremely difficult,
through the great suspicion which was continually excited
in the minds of the different contending parties,
under an idea that persons going from their places of residence,
in this season of commotion must have some sinister motives, and would,
as opportunities presented,
prove inimical to the cause in which they were respectively engaged.
Thus in many instances even going to religious meetings, was,
in the apprehensions of the persons in power,
deemed as sufficient evidence of treacherous designs, concealed under the plausible,
yet insincere, profession of religious duty.
Accordingly, after visiting several meetings in the state of New York,
returning into New Jersey, they were stopped by the military, who,
finding that they were innocent men, discharged them,
but soon after they were again apprehended, taken to Newark, and after some detention,
sent under guard as prisoners to Princeton, where they were examined by the governor,
(Livingston), and council, being supposed to be guilty of treason;
before whom he made the following defense:

The Words of a Prisoner Who had Liberty by the Governor
and Council to Speak in His Own Defense,
Supposed by Law to be Guilty of Death

I am glad of liberty to speak in my own defense before the Governor and his council.
I hope you are moderate, considerate men,
and will hear me patiently while I speak forth the words of truth and soberness.
We live, when at home, in Berks county, Pennsylvania;
I have been looked upon as a minister of the gospel among the people called Quakers,
from about the twenty-second year of my age;
and under the exercise thereof have travelled much in America,
and visited the meetings of Friends generally from Nova Scotia to Georgia,
and many of them several times over.
And in this great work I have ever observed the good rules of discipline used among us.
When I have felt my mind drawn in love towards my brethren in any part of America,
I have endeavoured first to get fully satisfied in
my mind whether it was the Lord`'s will or not;
and then, after being confirmed by turning the fleece, that it was his requiring,
I have always laid it before my brethren at the monthly meeting for their approbation,
and in like manner so at this time,
but never met with so much trouble upon the like occasion before;
for after I was fully satisfied it was the Lord`'s requiring,
by looking at the difficulties and dangers I should be exposed
to in crossing the lines of contending parties,
I became weak and fearful.
I thought I would mention my concern to the elders in a private way, which I did,
but received no encouragement from them to speak of it to the monthly meeting.
I then concluded to take no more thought about it, fearing it was a delusion;
but I was followed with the judgments of God for disobedience,
insomuch that the nearest connections in life became withered in my view;
and in this sad condition I came to a conclusion
that I would endeavour to obey the Lord`'s requiring,
although I might lose my natural life in the pursuit thereof.

I spoke of it to the monthly meeting, and after solid consideration,
they gave me a certificate signed by the elders and heads of the meeting,
which I have in my pocket.
We then proceeded on our journey, and crossed Delaware at Coryell`'s ferry,
and visited the meetings generally until we came to the North (Hudson) river,
which we crossed about four miles below Poughkeepsie,
and rode through the town some miles eastward, to a meeting,
and so visited the meetings generally in that government
without any interruption until we came to White Plains,
where we were stopped by the guard.
We told the lieutenant we were going to Mamaroneck meeting; he gave us leave to go,
but afterwards sent a horseman for us,
who informed us we must have a few lines from the colonel before we should go.
We rode back four or five miles to the colonel`'s,
who gave us a pass to go to Mamaroneck meeting, and from there we went to West Chester.
After meeting we went to the water side to go over to Long Island;
there was no boat there.
We made a smoke for a signal to the ferryman on the other side to come for us,
which he did; but informed us what we might depend upon,
that he was under an obligation to send all strangers
that he brought over to the colonel`'s at Flushing.

When we were over,
he sent a guard with us to the colonel`'s. We informed him our business on the island.
His answer was to us, if that was our business, it was a pity to hinder us.
He readily gave us a permit to travel through the island.
We visited eight meetings.
I think we were at a meeting every day we stayed there, and when our service was over,
we crossed the Sound to New York, where we had two meetings;
and when we were clear of that place, we, with the assistance of our friends,
got a pass from the chief commanding officer of that place,
to cross the North river at Powles Hook.
When we were over, I gave that pass to the colonel,
who went up stairs in a private chamber.
While I stood at the door there came an officer,
(as I thought by his dress,) and asked me if I was not afraid to go among the rebels.
I told him I was innocent, and was not afraid to go among my own countrymen.
The colonel sent for me to come up to him.
He gave me our pass, with an endorsement on the back of it, to pass the picket guards,
and offered me a newspaper, and told me I might divert myself as I rode, in reading it.
I told him I had nothing to do with politics, neither did I incline to read newspapers.
He told me I was at my liberty, and so we parted.
We had not gone but a few rods from the door until a soldier commanded us to stop;
he began to untie our greatcoats and search our bags.

When we were in New York, our friends told us of a judge whose name was Fell,
that had been a prisoner there thirteen months.
When he was first taken he was put in the Provost, and he, being a tender man,
in close confinement, was not likely to continue long.
We were informed that ten of our friends joined together to do their utmost,
by treating with the officers, for his liberty in the town, who at length obtained it,
by being bound in the sum of one thousand pounds for his good behaviour in the city.
This judge behaved himself so well as to gain the good will of the officers,
who gave him liberty to go home to his family, upon parole of honour.
Our friends considering the difficulties we might
meet with when out of the English lines,
thought it best for me, (as the judge was yet in town,) to go to him.
A friend went with me, whose name is Henry Haydock.
After that friend, who had long been acquainted with me, had recommended me to him,
and made known to the judge my circumstances, he said he was a prisoner,
and could do but little for me, but what he could he would.
He informed me he had a son who was a major, that lived about Hackinsack.
If I could find him, and tell him that I had seen his father,
he believed he would show me kindness; and if he saw him before I did,
he would speak to him concerning me.
I asked him if he dare write a line to him.
The judge thought it not safe.
He gave me his name on a small piece of paper, and told me his son would know his hand,
(which I have in my pocket.)

We went on our journey from Powles Hook, and travelled near twenty miles,
when we were stopped by the guards, our bags taken off and searched.
We inquired for major Fell.
They told us he lived many miles from that place;
and informed us of a major who lived four or five miles back,
where we went without a guard.
After that major examined us and searched our pocketbooks,
and had seen judge Fell`'s hand writing, which he knew,
he gave us a pass to the highest officer in Elizabethtown, which I have with me.
We went forward through Hackinsack, and came to Passaick river,
then crossed the ferry to a little village, where we were stopped by the guard,
our bags again taken off and searched thoroughly, but nothing found that was offensive.

Soon after there came along the road a major in a wagon, who stopped and came to us,
and in a very furious manner, asked us where we had been.
I told him we had been to New York.
He asked me if I did not know that there was a strict law against it.
I told him I thought that law was not made for such men as we were.
Then he, in a great rage, ordered the guard to bring us down to Newark;
and we were had there before a judge, a justice, and two majors.
After examination, we were sent to the guard-house,
where we were closely confined that night.
The next morning we were sent for to the major`'s house,
where was a justice who read to us the law, which we had not before heard;
by which we understood our lives were forfeited.
We were then had to the judge`'s house,
where our guard received orders to take us to the governor`'s.
The judge and his officers blamed us much,
that we did not go to the governor`'s at Poughkeepsie, +++[+++in the state of New York,]
in order to get a pass to go to York or Long Island.
We did not know it was death by the law,
until we had rode between thirty and forty miles below Poughkeepsie,
and then we did not know that it was possible for a stranger to
obtain a permit from the governor to go within the English lines.
And concerning deceiving the colonel at the White Plains,
in not telling him we were going to New York, if he had asked me the question,
I believe I should have told him the truth.

When I heard it was death by the law to go to Long Island and New York,
I was struck with a serious sadness, and did not know what to do.
To go forward, it was death by the laws of the land,--and to go homeward,
it was death by the law of the Spirit of life.
But after considering the matter calmly in myself, I concluded to go forward,
with a strong resolution to keep myself entirely
clear of those crimes for which the law was made,
and in so doing I should be innocent before God,
and more excusable before my countrymen at my return.
And I can assure the governor and his council,
that I have not said or done anything knowingly or intendingly,
that would injure particulars, or my countrymen in general:
and let the governor and his council judge whether I am guilty of death,
or further confinement.
If guilty, I must endeavour to suffer patiently, according to your laws;
but if the governor and council should judge me innocent, I desire a pass to go home,
and liberty in it to go back to Plainfield, Rahway, Shrewsbury, Squan, Squankum,
Barnegat, Egg Harbours, and Cape May, from which place I intend to go home,
if the Lord permit.

It would seem as though this was all that he said;
but his humility has operated to the suppression
of what he further expressed to the council;
namely, that if his visit should be judged a capital offense,
which must be punished with death, he only might suffer,
and his companion be permitted to go home,
as his only motive was merely to accompany him in the journey.
The governor and council, after hearing this simple, undisguised relation,
being conscious that nothing but a sense of religious
duty could have induced him to undertake such a journey,
in a time of extreme difficulty and peril, freely,
and with that magnanimity which ever accompanies genuine benevolence,
granted the following pass:

Princeton, 26th May, 1778.

Council of Safety, State of New Jersey

Abel Thomas and James Thomas, inhabitants of Pennsylvania,
being sent under guard to the President and Council
of Safety by two magistrates of Newark,
for having been into the enemy`'s lines in the city
of New York and Long Inland without passports,
and suspected of designs injurious to the liberties of America: the Board,
upon hearing their defense, were satisfied of their innocence,
and have reason to believe,
that their journey to the several places which they have visited,
was undertaken on a religious account,
and agreeable to their declared intention to the
meeting held at Maiden creek the 25th day of March,
1778,
of performing a religions visit to the meetings of Friends
in part of the Jerseys and part of New York Governments.
The Board therefore discharges the said Abel and James Thomas from their present confinement:
and they being further desirous to visit the meetings of their friends at Plainfield,
Rahway, Shrewsbury, Squan, Squankum, Barnegat, Great and Little Egg Harbour,
and at the Capes,
and this government being unwilling to obstruct any
society in the exercise of their religion,
the said Abel and James Thomas are permitted to pass to the nine places last mentioned,
and then to the state of Pennsylvania.

William Livingston, President.

Some time after his return home,
his mind was drawn in the love of the gospel to several places in Pennsylvania,
and two of the adjoining states, which being spread before the monthly meeting of Exeter,
they granted a certificate, dated eleventh month, 1779,
leaving him at liberty to perform a religious visit
to the meetings of Friends in parts of Pennsylvania,
Maryland, and Virginia.
And also in 1761, with the unity of the monthly meeting,
and having Amos Lee for his companion, he visited meetings in Virginia and Carolina,
passing through very great difficulties, as the country was much infested by a lawless,
murderous banditti, who, for the sake of plunder,
frequently shot down innocent people as they were riding along the roads.
When at Camden, in South Carolina, they were taken up as prisoners by the American army.
Being kept with the soldiery several days they at length obtained a discharge,
as appears by the following extract of a narrative which he sent to his friends:

To Friends of Exeter Monthly Meeting, Berks County, Pennsylvania

Dear Friends,--

I believe it my duty to give you a short account of the
reason of my long stay from my family and friends,
and why I did not return with my companion, and the reason why my companion left me;
as also to give you to understand, that I am afflicted, but not forsaken.
When we came to a meeting at Pedee, in the south part of North Carolina,
a large American army passed by us into South Carolina,
and encamped in the road to a little meeting, not far from Camden.
I thought I saw clearly, that it was best for us to follow them,
and we gave ourselves up, as prisoners, to the captain of the provost guard.
The officers gathered about us.
Our horses were taken from us,
but our saddles and saddle-bags we had with us in our confinement.
Our papers were soon demanded, and read over, and we were closely examined:
some of our papers were sent to the head general.
They gave us to expect we should have a pass to go home, if we would promise to go;
but I could not make such a promise,
being bound in spirit to do my endeavours to visit Friends in South Carolina,
if not in Georgia.
In the time of our confinement, we had the company of several officers, one at a time.
They behaved civilly, but were full of talk and foolish imaginations concerning us.
Let me never forget my Master`'s kindness in a time of need:
I had talk enough for them all, which they could not gainsay or condemn.
At length they concluded, yes, one of them told me, that I was a crafty fellow,
chosen by our yearly meeting in Pennsylvania to survey the southern states,
to the disadvantage of our country, and for the advancement of the British troops,
or words to that effect.
We were often pressed to promise to go home, which I as often punctually refused;
giving them such reasons for it which they could not answer.

We gave ourselves up to the captain on sixth-day in the afternoon,
and on first-day morning following, about an hour or two before day,
there was a great stir in the camp, the officers riding to and fro,
ordering the soldiers to make haste and parade ready to march.
When our captain had got his men in order, with many prisoners,
he honoured us so much as to rank us next to him,
and so he marched on with his naked sword in his hand, and we following him.
We marched near twenty miles, and then encamped.
When we first set out, I was thoughtful how we should get along, for several reasons,
if they marched far.
We had eaten sparingly the day before,
and then had but a little more than one biscuit and
a little piece of meat between us both,
and had our bags and great coats to carry; and what made it seem more trying,
the sand was deep and slavish, and my boots stiff and heavy.
The thoughts of these things, for a time, seemed grievous.
I began to inquire for my Divine Master, and when I found him,
I conversed with him as though he was present, and told him as though he knew it not,
that I had left my dear wife and all that I had that
was near and dear to me for the love I had for Him,
and did entreat, that he would not leave me now in a time of trial:
and he was pleased to hear me, and with an encouraging language,
conveyed to my understanding these words, "`Fear not, my servant, I will be with you.`"
The praise of all be given to Him, for he is worthy:
he did fulfill his promise to my admiration.

We marched fast.
I ate but little more than half a biscuit that day,
and yet could not perceive myself hungry or weary.
I found freedom to be cheerful in conversation with the captain and with his men.
The officers passing and repassing, generally took notice of us.
Some of them asked how we were.
I answered as I felt, with as much cheerfulness as I could.
We were now encamped in the wilderness under guard, but had liberty to walk out,
one at a time.
I went out that afternoon, from tent to tent, among the officers,
making known to them our circumstance, where we desired to go, and what our business was.
One of them promised to let us go in the morning.
I returned to my companion, laid down by him, but could not sleep,
although I had not slept much for several nights.
Remarkable it appeared to me,
that I should be well and hearty and lively without much food or sleep.
My dear friends, search for the reason.
I believe it to be the Lord`'s doing, and it is marvellous in my view.

The next morning I went to seek the officer who had promised to give us our liberty,
and after some time found him, and put him in mind of his promise.
He seemed to quibble, and put it off.
I thought he intended to weary me out, that so I would promise to go home.
I went to the head officer, and made my complaint, and he, in a friendly way,
told me that we should soon be released.
Soon after, that officer who had promised us a permit, called me to his tent,
and wrote a pass for us; and when he had read it to me,
my spirit was raised with zeal for my Master`'s honour, and so I told him,
that I was not to fear or be frightened by men when in my Master`'s cause:
"`Must we indeed go right home without a guard!
No, send a guard with us for the safety of your country.
Yes, we have concluded to go homeward about one hundred and fifty miles,
to a settlement of Friends about New Garden, and when we have visited them,
if I find my mind easy to return home to my wife and children, I shall be glad.
But if I find my Master has any more service for me in this part of the country,
I desire to be enabled to return to South Carolina, if not to Georgia,
visiting my friends; and if I should return through this army, when you see me ride on,
then remember what I tell you now.`"

Officer.--If you return here again, you may expect severity.

Answer.--I do not fear what your army can do to me,
for I know that you can have no power over this body,
except you receive it from above for some good end.

He then looked me full in the face, and perhaps saw the tears begin to run down my cheeks.
He gave me his hand, and wished me a good journey, got on his horse, and rode off.

Our horses were given to us;
we parted with our captain (of the provost) as with a friend,
and with a raised voice bid his men farewell, and wished them a better way of living,
which they returned, with gladness for our release.
We had about sixty miles to a Friend`'s house at Pedee, from where we came.
I thought our being among them was no disgrace to our Society.
O how good it is for us to live near the Truth!
Walking in the light, we should be at no loss to know what to do, or where to go,
or how to behave ourselves before men for the glory of God,
and for the safety and peace of our souls.
I have been much preserved in such a state since I left you:
I am unworthy of such great kindness.
The thoughts of the many days, weeks and months, which, in time past,
I have spent in the unnecessary cares of this world, do at times grieve me: that,
and the sense I have of the state of the churches,
is the greatest affliction which I meet with.
I find hard work among Friends in these southern provinces,
but have been helped by my kind Master, to proclaim his great name,
although in a clumsy and uncustomary way: I generally feel relief to my burdened,
troubled soul.

I am in a few days intending to set out for South Carolina again,
not knowing what may befall me there.
My greatest concern is that I might be obedient to my Master.
I cannot see the end of my journey, nor the road home so clearly as usual.
It may be you may see my face no more; and if it be so, I entreat you,
in that love which I feel for you, that you show kindness to my dear wife,
and watch over my children for good.
The reason of my beloved companion leaving me--I
first proposed it to his consideration for your sakes,
lest you might be uneasy; and after considering and looking at it,
he found freedom so to do.
It is no small cross for me to part with him;
we have travelled together in love as brethren in tribulation.

My love to you all, my friends and neighbours.

Abel Thomas.

New Garden, North Carolina, Fifth month 6th, 1781.

After being some time in the vicinity of New Garden, North Carolina, Amos Lee,
finding his mind released from further prosecution of the journey, it was their judgment,
that it would be best for him to return homeward;
but being closely united in the bonds of gospel fellowship,
and in that inward endearment which, through the love of Christ,
connects the real members of his church, it was no easy matter for them to part.
Yet seeing it necessary, with the tenderest desires for their mutual preservation,
resigning each other into the hand of Him, who in great condescension,
had hitherto preserved them in much tribulation, they separated.
Abel, after this,
not feeling easy to omit making a further essay towards
the fulfilment of his prospects of religious duty,
proceeded to South Carolina, where the trials of faith,
and the remarkable deliverances vouchsafed to him, in this perilous travel,
are in some degree set forth in the following relation.

In a thankful sense of preservation by a strong arm through many dangers and deep conflicts,
both within and without,
which I met with in my journey through South Carolina and Georgia,
do I write these lines, in order to encourage the weak, the poor afflicted people of God,
to trust in his powerful arm, which does work salvation and deliverance,
by bringing strange and unexpected things to pass.
He is greatly to be feared, and loved, and adored, by his afflicted children.
They who know him, and do their endeavour not only to know but to obey,
have no reason to distrust his care and great power to preserve,
not only from being taken by the secret and subtle invasions of Satan,
but also out of the hands of bloody and unreasonable men.
These things I have experienced in the great deeps,
and do certainly know that the Lord`'s arm is not shortened that it cannot save,
nor is his ear heavy that it cannot hear.
When I consider my own weakness and inability as a man,
and as a servant engaged in so great a work,
and also the grievous besetments and terrifying storms
in which the subtle serpent arose against me,
my mind is humbled; well knowing who preserved me in the depth of distress,
when my soul was taken with fear,
and my body almost given to the wild beasts of the wilderness:
then the language of my soul was, make haste, my beloved, for I am almost overwhelmed.
I will make known to my brethren his wonderful works,
and relate to them my travails and the exercise of my mind,
and give the praise to the great God of power through
his dear Son Jesus Christ who is worthy forever.

When we came near South Carolina, we were told that the country was all in an uproar.
Scouting parties from both sides were riding to and fro, killing one another,
and also peaceable men whom they found travelling,
except they knew them to be on their side:
and that they had determined to take no prisoners,
which we found to be in a great measure true.
When I heard this sorrowful news, it took deep hold of my mind;
for I had entertained a thought that I should die in that country, and as times were,
I thought I should not die a natural death,
but that I should be barbarously cut down by the light-horse.
I searched deeply to know whether my concern was right,
and my Master was pleased to manifest to me, that it was his will I should go forward.
We travelled on, visiting meetings, and generally alone, inquiring the road.
Friends were fearful.
They were advised by the most moderate persons in power, to stay on their farms,
except going to their particular meetings.
We met with none of these cruel men, although we could hear of them almost every day,
until we got within ten miles of the British garrison at Ninety-six.
We then approached a large scouting party upon a hill.
We could see them afar off, and when we came up to them, we found they were much afraid.
We showed the major our certificates, and asked him if we might go forward.
He said he would not hinder us, if we would venture our lives; for the rebels,
(as they called them,) had got between them and their garrison,
and were killing all before them.
I told him that I did not trust altogether to man for preservation.

We rode on, but had not gone far, until he and a negro came riding after us.
He ordered his negro to ride on some distance before, and if he saw any man,
to ride back and tell him.
The major rode in between me and my companion.
I felt uneasy in my mind while he rode there, and we endeavoured to shun his company,
but could not.
His negro wheeled round his horse, and hallooed to his master, "`Rebels! rebels!`"
The major stopped, and turned about to run; then calling to his man, asked, "`How many?`"
He answered, "`Two,`" He wheeled back again, and out with his pistols,
and rode furiously towards them; but found they were his own men.

We travelled on, lay in the woods not far from the garrison,
and next morning passing through the town, were detained some time by the picket guard.
Being conducted to the head officer, he appeared kind to us,
and invited us to breakfast with them.
I acknowledged their kindness, but told them I desired not to be detained then,
for I expected to be called to an account for passing through that place.
They, with sorrow, signified they would not detain us to our hurt;
and we were told a few hours afterwards, that general Green surrounded the garrison.
We visited the meetings on towards Georgia, and were told,
it was as much as our lives were worth to go over Savannah river;
that the Indians and white people were joined together in their bloody designs.
We had been so remarkably preserved hitherto, that we did not much fear them:
we rode the river in great danger, the water being so rapid, and the bottom so rocky,
that I never rode in such a dismal place before.
It was well we had a pilot who led us among the rocks;
for I thought if our horses had stumbled,
they must have been washed away by the rapidity of the stream; but we got over safe,
and travelled on towards the settlement of Friends.

While riding a small path in the wilderness, two men overtook us,
and in a furious manner, with great rage, ordered us to stand,
and with terrifying language were raising their guns to shoot us.
I desired them to stop a little while,
that we might clear ourselves of those high charges.
They gave us a little time, but soon broke out in terrible rage,
with blasphemous language, and one of them was cocking his gun.
I desired them to have a little patience; I had something to say:
and so we remained for about ten minutes.
Then they turned round to consult between themselves privately.
I heard one of them ask, if they should kill us; the other answered,
"`I hate to kill them:`" and after some more private discourse, turned to us,
and ordered us off our horses; they got on ours, led their own, and so rode off.

Our pilot riding a poor beast, his apparel also being poor, they said but little to him,
and took nothing from him.
Being now left in the wilderness,
we soon came to a conclusion to return to Friends at Longcane, from where we came;
but how to cross that large and rapid river Savannah, we could not conceive.
It looked unlikely that we could ride two at a time on so weak a creature,
neither could we wade it.
We sought for a canoe, and seeing one on the other side, called, in order to get over.
A young man came to the canoe, and inquired who we were--asking if we were rebels.
My companion told him we were friends to the rebels.
He then said, we were damned tories, and should not come over.
We then went down the river to a place where some had forded in low water.
My companion and pilot stripped themselves, and being good swimmers,
they got on the weak beast, with their clothes between them, intending,
if the creature sunk, to swim out, and if they got safe over,
one of them would come for me.
I could see but little of the horse until they got to the other side, which was,
I suppose, about two hundred yards: sometimes the water ran over the saddle,
and my companion coming back for me, we also landed safe,
then travelled on to William Miles`'s, from where we came,
and a kind friend he was to us.

This was a trying time to me; not so much on account of the loss of my property,
as for the absence of my Beloved, who had been my preserver and conductor.
I was afraid I had offended him in going so far.
I endeavoured to keep still and quiet in my mind,
and soon perceived I must return to that bloody place again.
When I made it known to my companion, it was grievous to him,
and after a time of silence,
he told me we had been so remarkably preserved while we were within our prescribed limits,
he thought we had no business there; if we had,
it appeared to him unlikely that we should have been stopped: and further,
that I had not liberty by certificate to visit the meetings in Georgia.
This discourse from a valuable friend, so highly esteemed by me,
and also by his friends in general, struck me deeply.
I told him I desired to look more deeply into it.
This was the next morning after we came to the aforesaid friend`'s house.
I inquired for work, and kept closely at it for two weeks,
my companion not being able to do much; my desire was,
to keep him and myself from being chargeable.
At that time I could see no way home, nor the time to go back again.
For several days I was in great distress, and there was none to help me;
often looking towards my dear wife and children mourning for me,
and I not knowing how long I should be detained there,
or whether ever I should see them again.

One night as I lay bemoaning my sad condition, as though I had offended my Master,
whom I had loved above all, I cannot express the anguish of my soul at that time;
and in the depth of distress, a language sprang livelily in my mind, "`Stand still.`"
A language which I understood at Camden when a prisoner there,
was now with life revived and renewed, "`Fear not, my servant, I will be with you.`"
O, how was my troubled soul revived!
All doubts and fears vanished away, and in this pleasant and favoured state I said,
"`It is enough, Lord!
I want no further confirmation; I will go or will stay at your word, only be with me.`"
Indeed, the place where I was seemed so pleasant for some time after,
that I thought I could live there all my days, if it was his will,
without being much concerned about home.^
footnote:[When relating this occurrence to a Friend, he said in substance,
that the room was so filled with light,
attended with such consolation in the Divine presence,
that in the flowings of heavenly joy and peace he felt nothing lacking to be supplied.]
I soon informed my companion that I intended to travel towards Georgia, and that,
as by his discourse a few days before, he thought he had no business there,
I should leave him at his liberty; but desired he would stay here for me a certain time,
and then return, if I came not.
After serious consideration, he told me he could not be easy to let me go alone,
and if I went, and died, he would die with me.
A day soon appeared for me to travel on, and also to write a letter to general Green,
who was then about thirty miles off, fighting against Ninety-six.
He soon read my letter, and granted my request, as follows:

Mr. Abel Thomas, and Mr. Thomas Winslow, Long-cane

Camp, before Ninety-six, June 7th, 1781.

Gentlemen,--

Your letter of the 6th is before me.
From the good opinion I have of the people of your profession,
being bred and educated among them, I am persuaded your visit is purely religious,
and in this persuasion have granted you a pass;
and I shall be happy if your ministry shall contribute to the establishment
of morality and brotherly kindness among the people,
than which no country ever needed it more.
I am sensible your principles and professions are opposed to war,
but I know you are fond of both political and religious liberty.
This is what we are contending for, and by the blessing of God,
we hope to establish them upon such a broad basis,
as to put it out of the power of our enemies to shake their foundation.
In this laudable endeavour, I expect at least to have the good wishes of your people,
as well for their own sakes as for ours, who wishes to serve them upon all occasions,
not inconsistent with the public good.

I am, gentlemen, your most obedient humble servant,

Nathaniel Green.

Head-Quarters, June 7th, 1781.

Abel Thomas has General Green`'s permission to pass and repass through this country,
behaving with propriety.
Nathaniel Pendleton, Aid de Camp.

[.asterism]
'''

We set out early in the morning on foot, serious and deep thoughts attending my mind.
We seemed like sheep going a second time before the slaughter,
without any outward obligation: we travelled about twelve miles, crossed Savannah river,
and came up with a colonel and his men, who had got there the night before.
A captain looking earnestly at us, began to examine what our business was,
and hearing the account we gave, (slender indeed in his view,) namely,
"`to visit our brethren at Wrightsborough,`" he appeared surprised and mistrustful;
and asked us for a pass, which we gave him: he ordered us to follow him,
and led us to the colonel.
Our certificates, general Green`'s friendly letter, and permission, being read to him,
they asked why we were travelling on foot.
We told them we were robbed not far from that place, about two weeks before.
They said they had heard of us down at Augusta, and if we would stay,
they thought they could find our horses, for they knew who had them.
And as I was describing my horse, a soldier said, he thought my horse was in the company;
and I soon found the horse, saddle, and bridle: tor that wicked man had just ridden up.
I informed the colonel, who had him immediately taken and put under guard,
and then sent out a scout after the other, who had my companion`'s mare, saddle,
and saddle-bags, and confined him also, which greatly surprised them.
They sent for us, and desired we would forgive them.
We inquired where our goods were.
They readily informing us; we told them that all we wanted was what we had lost,
and that they would repent and amend their ways of living;
that we could forgive them and do them a kindness if it lay in our power,
although they had injured us.
They appeared low in their minds, for the colonel declared they should be hanged,
as many accusations of their wickedness and barbarity came against them.

We got the principal part of our goods, lodged with the soldiery that night,
and next morning rode to Friends`' settlement, I hope, with thankful hearts,
and visited the meetings of Friends both at Wrightsborough and at New Purchase.
Finding my mind clear, I turned my face homewards, and as I rode,
a hope renewedly revived, that I should see my little family again.
I felt them near to my heart,
although by computation eight hundred miles distant from them.
We crossed Savannah river, and travelled towards Ninety-six,
where the armies were fighting; and when we drew near,
became doubtful how we should pass, as the cannon were firing fast,
and the road we were in, leading immediately to the British garrison,
we knew of no way to escape; but a friendly man overtook us,
and told us that he would pilot us round, and a difficult path it proved;
sometimes we were close by where they were fighting, or firing upon the garrison:
and as we passed through the skirts of general Green`'s army, the cross officer,
whose prisoner I had been when at Camden, saw me ride on as I before had told him.
He called to me: "`What! old fellow, are you there?`"
I answered him according to his question.
He asked how I came to deceive him.
I replied, I had not, and that he knew it.
He came to me, took me by the hand in a friendly way, and said,
he hoped I had done no harm.
I told him, I did not intend harm; and with some more friendly conversation we parted.
Just before we got round into the road,
general Green`'s men fell upon a fort or redoubt but a little way from us,
making a terrible noise.
There was a great stir among the people, some running one way, and some another;
some hiding behind trees; we rode smartly on,
and could hear them for about seven miles without intermission.
We passed on towards North Carolina, without any other remarkable interruption.

As for my service and exercise in the ministry,
I have left it to the judgment of my brethren.
My Master had a service for me there, and I trusted my life in his hand, travelled on,
and so obtained a reward which is more precious than gold.

Abel Thomas.

Seventh month 7th, 1781.

He was favoured to return to his family and friends in peace,
and delivered up his certificate, and gave an affecting account of his exercises,
and in the following year, 1782,
was again drawn forth in a visit to Friends in some parts of Pennsylvania.
To mention all his religious visits may not be necessary; but from 1761 to the year 1800,
it appears by the records of Exeter monthly meeting,
that in addition to his religious engagements among Friends in his own neighbourhood,
he was very often from home on this weighty service.
In 1799,
while engaged in a visit of gospel love to the southern
states he wrote the following letter to his wife:

Second month 19th, 1799, just returned from the Tennessee country, towards New Garden.

Dear Ellin,--

I received your letter last first-day three weeks, at Reuben`'s creek, in South Carolina,
about two hundred and forty miles from Charleston,
the evening before we started for the western territories.
We went not to Charleston, but sent for our letters from Bush river,
and had near missed them, as we were about forty miles on our way toward the mountains.
I was glad to see your hand-writing,
and to hear that you were well,--and of your resignation in my absence,
under the encumbrances and fatigues of business.
As there seems a necessity for it at this time, I hope your doing what you can,
and resigning, will be the likeliest way to be blessed with success.

I am well in health, and have been so ever since I left home,
except six days in Virginia, where I missed two meetings,--and in the western country,
but was able to travel.
We have prospered in outward travel; but as to travail and exercise of mind,
I am often reduced very low;
which I believe is for my good,--for the more powerful exaltation of Master`'s name,
in myself, and it may be, in some others.
But so far I can say, that it is always well with me,
when I am sensible that Master is near, but when he hides his face my soul is troubled.
All my travelling through this wilderness country, so far from home,
is so little hardship, that I can scarcely give it that name, when Master is present.
But when he withdraws from me,
there is nothing in this world that I can please myself in thinking of.
If I look towards you +++[+++his family,]
there is but little satisfaction in your company in his absence.
I cannot rest neither at home nor abroad, when I am afraid my ways do not please him.

I have wondered sometimes, knowing so much of his care and goodness to me,
that I could not be easy and resigned in his absence;
always rejoicing in hopes of his return.
But my own weaknesses are against me, when I am reduced into a state of suffering,
and I inquire deeply into my behaviour before him.
I long for the time to come,
that I might make my conduct upright before him in all things.
But far from that,
I often find I have not been so steady in watching as was pleasing to him.
My words in conversation have not been so few and savoury as would be most for his honour.
My haste in travelling, in order to get home soon,
has hardly been reputable among my brethren,
and many more weaknesses came against me in the south.
These little weaknesses are hardly noticed by many professors.
But they are as motes in the eye, that obstruct the sight;
they are as little foxes that hinder the growth of the vine.
They are as leaks, hardly perceived in a time when we think all is well;
but a leak is wasting the substance, if it be but through a little worm hole.

I was hinting at something that befell me in the
south,--so far as I can describe it in words,
I shall let you know, as a most endeared companion.
I perceived for many days, that Master was about to leave me to myself,
that I might see what I could do without him:
or that I might learn more perfect obedience in watching,
both on the right hand and on the left.
When I understood it so,
I became more and more afraid,--inquiring deeply into my conduct before him.
My many weaknesses appeared before me,
and I looked carefully to see what would become of me, if he should withdraw from me,
and hear no more of my secret cries.
Under these considerations I was alarmed;
but remembering his lovingkindness in times of deep distress,
I put on all the strength I could gather, and resolutely determined to hold him fast,
by doubling my diligence, but was not able.
He was stronger than a lion; he was swifter than an eagle.
I looked after him, with desire; but found myself as a worm, with neither wings to fly,
nor feet to run.
I was in a great strait to know what to do.
But calmly considering how it was with me, I saw no way but to be still and resigned,
and to endeavour to nourish a hope of his return.

But oh! my great weakness and impatience in waiting!
Feeling myself so disabled, and my great enemy roaring against me,
it seemed as if a day of great trouble was approaching.
I was ready to say with Agag to Samuel, "`Surely the bitterness of death is past.`"
Hope of Master`'s return was almost lost.
I could not hold confidence in the remembrance of past favours;
for imagination did work hard against me.
However, it appeared to me that I should be of no more use in that country.
So I looked towards home, inquiring into my affairs there.
Oh! how grievously my encumbered circumstances gathered all around me, as mountains;
so that I could see no way out.
I then remembered the wormwood and the gall before I left home,
when I had a large draught of it.
Then can you, my dear Ellin, understand, or conceive the weight of my distress,
in the South?
Although it was so,
I was favoured with a little reason to believe that there is a God so wonderful in power,
that all things are possible with him,--and that all power was given to his dear Son,
my beloved,--and that if I did not love him,
I should not be so distressed in his absence: and he does love them that do love him.

My faith began to increase; and when I found it so,
I was ready to burst out with vehemence of desire, and with a most lamentable cry,
must I return home without my Beloved?
Oh! no, rather let me die here, and be buried in a far country,
no more to be remembered by the living.
But I soon felt that he was coming.
The mountains began to skip like rams,
and the little hills like lambs before him,--and
his divine presence overshadowed my tabernacle.
I was silent, with wondrous admiration.
I was afraid, and ashamed of my own littleness and unworthiness, in the presence of Him,
so wonderful in strength; but I was filled with humble thankfulness.
I did think, under such a covering, "`the morning stars sang together,
and the sons of God shouted for joy.`"

And now I think myself as happy, under perfect obedience,
as I could wish on this side of eternity--although far absent from home.
"`For lo! the winter is past;
the rain is over and gone,--the time of the singing of birds is come;
and the voice of the turtle is heard in our land.`"

My dear Ellin, I have a great deal to say to you that I have not time to write.
I hope to see you in a little time; but not much before the middle of the Fourth month.
My love to you is great, and to my children all,
without knowing which of them I love most.
In proportion will my grief be, if they should, either of them,
give way to bad practices, and lose themselves in this deluded world; and more so,
in that I have, in the course of my experience,
sensibly felt of the powers of the world to come;
and the most exceeding excellency of that glory among the saints in light.
As also, on the other hand,
I have sensibly felt of the powers of death and the pains of hell, as it were,
among the miserable.
Now, if my dear children should take wrong courses,
how should I who do love them so well, bear the mournful sight?
It would be likely to bring down my bald head with sorrow to the grave.
From your loving husband, with love to my dear children.

Abel Thomas.

In 1801, he removed with his family to Monallen, in Adams county, Pennsylvania,
and while a member there, was also diligently engaged in the work of the ministry,
both at home and abroad.
While engaged in a religious visit to New York and Pennsylvania,
he wrote the following letter to his wife:

Hudson City, 19th of Twelfth month.

Dear Ellin,--

I thought to have written to you before this time, but have had no safe opportunity.
I have been among the mountains and back inhabitants;
where many meetings have been settled since I was this way.
Had it not been that Friends were kind to me, I had not been here so soon by many days.
They frequently sent forwards ten or fifteen miles, to lay out meetings for me;
the days being so short that I could not ride from one meeting to another
in time for them to give notice fully to their friends and neighbours.
I had often to ride in the night, in the snow, and in the rain,--dismal roads.
I was often sorry for my companions: they appeared, some of them,
almost overcome with the cold.
My little mare carried me over all, and has not yet thrown me;
and I can`'t find that she is falling away.

When I left home, I had the pleasure of riding alone to the place I intended to stop.
I was at Exeter meeting, and also at Hardwich, where Friends had notice.
It was a meeting of encouragement to me.
Often, in travelling, I had to look back at my little family whom I had loved, may be,
more in deed than in word;
laying out what great things I might have done for them if I had stayed at home,
and felt myself as lightsome and as peaceful as I then was.
But, turning to view how I felt some time before I left home,
I found myself almost as happy as I could wish,
and was seldom troubled with discouraging thoughts.

I arrived there +++[+++Cornwall]
on sixth-day, in the afternoon--the next day I rested.
Friends laid out nine meetings for me to attend the next week.
I was at Cornwall on first-day; the next at Upper Clove, and the third at Lower Clove:
at both these last, silent.
Something befell me here, so different from what I was used to,
that I thought it no harm to let you know in writing.
It was a large meeting,--the house crowded with Friends and others.
I perceived a good deal of uneasiness before meeting closed:
and when it broke up there were but few Friends gave me their hands.
The friend with whom I lodged the night before,
had told me that there was a friend who had got his
horse shod in order to pilot me to the next meeting.
This friend led me to him, and asked him if he was ready to go with me.
He answered, he had thought to go; but something had fell in his way so that he could not.
It appeared to me as a come off.
From this meeting to the one to be held next day, was called twenty-six miles.
I went to my creature, and led it towards the people,
who appeared to be in haste to get away.
I stood with my cane in my hand; and no Friends came to me,
nor asked me to go home with them.
After some time, I saw my old friend T. T. fixing his wagon, to go off.
I led my mare to him,
and pleasantly and cheerfully asked him where I should
get something for my creature to eat.
He told me that I might come with him.
I accepted his kindness, and followed him home.

After some time, I began to inquire the way to the meeting.
He told me it was a shame to let me go alone, and that he would go with me a little way.
I let him know I did not desire him to go;
he being old and feeble--that I was used to travel--and if he would
give me directions to the great road up the river,
I might ride until bedtime,
and lodge at a tavern or private house--and that
I was not afraid of getting there in time.
The old man went with me some miles, and left me at a Friend`'s house.
I got up early next morning, and the friend`'s son went with me.
We got there just as the meeting was sitting, and an encouraging meeting to me it was.

I do not blame the Friends.
It`'s likely they thought that I was a poor, unworthy old man.
I thought so myself.
It is likely they thought I had no business to put them
to so much trouble,--not only in attending the meeting,
but in spending their time giving notice in the neighbourhood.
I thought it was not far from being right, as to myself, in using me so;
for I have often been telling you that Friends sometimes were too fondly kind;
and it is more fitting for me to know the feeling of being publicly despised by brethren.
It did me no harm; I was not in the least disordered.
I compared such treatment with that of too much fondness;
the latter much more disagreeable.

[.asterism]
'''

Dear Ellin, I have a great deal to say to you.
I feel you often near to my life.
I may just say that it is well with me.
I have a good Master--am so well harnessed that I find myself
a full match for every obstruction I have to meet with;
yet often see myself very little and low, and much spent; yet even in that,
I feel myself, in a good degree, happy, in a resigned state,--from under condemnation.
I say I feel my yoke is easy, and my burden light.
All that I have to go through in the day and in the night,--in
the snow and in the rain--is but little for me to go through,
hardly worth mentioning,--for the love I have for Him that has done great things for me.
I feel nearly united to the people, in gospel love; and from appearance, they to me.
Our meetings generally are held in solemn fulness, and break up under such a covering.
It is a great thing, to live near the Truth, where the wicked one cannot touch us,
nor endanger our safety.
This, I do desire for you and my children.--It is likely you are almost discouraged,
as to the things of this world.
Then, let us turn more actively to religious matters.
There is never-failing encouragement,
if we do all we can to please Him who is able to prosper us,
and to bring about matters beyond our expectations.

I have been at forty meetings.
From what I have been told,
there are sixty before me in New York government and Pennsylvania.
It is not likely you will see me home before the last of the second month.

Abel Thomas.

In 1812, he visited the meetings in New Jersey,
and in 1813 performed an extensive journey in the service of the gospel,
in the northern and eastern states.
While engaged in this, he wrote the following:--

Fifth month 3rd, 1813.

Dear Ellin,--

I am in good health, and do not know that I ever felt the depth of gratitude,
and endearing love to you, in all the time we have been acquainted,
as much as at this time, in remembering your care and concern for me,
when I was almost famished to death with hunger, and could not reach any encouragement,
either from above, or from beneath.
When you yourself were stained in my view;
when all things appeared sorrowful and discouraging to me, I did pity you,
and strove to hide the worst from you, but could not.
I thought I could hide it from my children, more than from you.
Oh! did I ever know such a time before?
It did grieve me when I saw your care and concern for me,
in using your endeavours to bear me up from sinking under discouragement;
when I could not give you any encouragement, though so cheerful and pleasant to me,
in using all your endeavours to moderate my grief.
I hope I shall never forget your lovingkindness to me, in that day of great trial.
I am bound, from the ties of endeared love to you,
to give you a particular account of my journey so far, both within and without.

When I left home, I had not gone far on the road,
before four friends from Ohio overtook me.
A+++.+++ T. rode up alongside of me, and began cheerfully to converse with me.
I was sorry they had not gone before me.
We had not rode far,
before she asked me to fall into conversation concerning my large experience in travelling.
I let her know, that I had but little or no experience.
That former experience was of little or no account to me,
but that my great concern was about present time;
and that I had no inclination to talk much about anything; that I rode slow,
and did not intend to mend my gait, and if they went on, I was content.
So I reined in my horse, and fell behind.
They went on.
I lodged at Abner`'s;
the next night at William Brinton`'s. Oh! the hunger and thirst that I was sensible of.
I had forty-six miles to Daniel`'s. It was between nine and ten, before I found his house.
I fared this day much as the day before.
When night came on, in riding slowly along, a good deal tired, I was ready to say, "`Why,
this is a long fast;`" and entreated that I might be favoured with a morsel of bread,
"`for I shall surely die to a sensible feeling of your presence,
which I have in time past greatly rejoiced in; and what good will my life do me,
if I am banished from your presence?`"
Admirable it was to me in all this long fast,
there was about me no melancholy or mourning, further than I have just wrote.
I could so clearly see my way,
and no other way by which I could see or feel any hope that I ever should
be favoured with that bread which I have so long suffered the lack of,
that I had hopes that the day was breaking, and the worst was past;
but oh! my great weakness continued.

Sixth-day in the afternoon, I rode to the city, very slow, to my lodging;
had agreeable entertainment, a little room, three story high, to myself.
But oh! my great weakness and poverty in spirit.
My friends soon gathered about me.
I was much tried.
They found something was the matter, and they must know what it was.
I let some of the most intimate and foremost friends know,
that I did not desire much company; and that they would do so much for me,
as to let friends know it.
But they would come.
I let them know that I was so old and hardened,
that it was out of the reach of man to do me any one good.
I attended all the sittings of the yearly meeting, save one:
but oh! my great weakness and poverty.
Yet I let my friends know, that it was not with me as they might expect.
I felt my feet upon that unshaken Rock that stands sure.

When the last sitting of the select meeting broke up,
my esteemed friend John Brown stopped me in the yard (who was about making ready
to travel with me to the eastward) until some of the foremost friends came out,
that had had no opportunity to speak to me, through all the sittings of the meeting;
they came about me.
George Dillwyn undertook to examine me, what was the matter with me,
that I kept so hid the whole week, out of the way of being useful among my friends.
I let him know that I felt no uneasiness in my mind concerning omission or commission,
in respect to the ministry or discipline.
"`That is not all we want to know;
what is the reason you will not go among your friends
nor allow your friends to see you!`"
I let them know that I had felt myself so weak, little and poor,
and was often afraid I had lost my sword; so I was afraid of much company,
lest through weakness, I might say or behave, in some respect,
so as to increase my great weakness and concern of mind.
I spoke to them in tenderness, and in the depth of humility;
which appeared to affect them, and lead them into tender sympathy with me.
It is likely some of them did know the necessary
qualification for a true minister to experience.
Seventh-day morning, when my two children,
my brother Amos Lee and his wife and daughter were about leaving me,
oh! the depth of my weakness, poverty, hunger and thirst, was painful.
I remember in time past, when anything came hard upon me,
I endeavoured to look to my Beloved for relief;
but now my Beloved has hid himself these two months and more, and I can find him nowhere.

But it was not long until he came to me; he met me and embraced me,
and let me know that he loved me and owned me as one of his children;
and the reason of his long absence was to try me,
and that I might be more perfect in love to him.
Oh! how did easy tears of joy gush out of my eyes, and run down my cheeks!
I seemed to be swallowed up in the Divine presence: my eyes are, with weeping,
become sore.
I cannot refrain at times, in company with my friends, and walking the streets,
in thinking how careful he was of me in the great deep,
when no man could do anything for my relief,
when the adversary was so chained that he was not
permitted to tempt me with melancholy or despair,
all this long fast.
I do now find myself in the depths of humility, where I have nothing to fear;
and do feel myself as bold as a lion, prepared for battle in his behalf.

Tomorrow morning, the 4th, I am to leave the city,
going up to Wrightstown monthly meeting, fifth-day at Middletown--sixth-day to the Falls,
where John Brown, my companion, lives.
From there the nearest way to Long Island; expecting to attend all the meetings,
before the yearly meeting in New York; where I hope to meet a letter from you,
and I do intend to send one to you.

I may say, you are my most endeared friend in the world.

Abel Thomas.

At the close of the New York Yearly meeting, about the beginning of the sixth month,
he wrote:

Dear Ellin,--

I am in New York, in good health.
Last evening I received your letter,
which was so agreeable to me that I have read it over and over;
and it seemed a little to me as though you had been dead, and were risen again.
I was so completely weaned from you that I could see but little more comeliness in you,
than in another woman; but now,
an object of admiration as near and dear to me as my natural life.
I am travelling on in hopes to be with you again.
As it has been with me in time past, so it is now.
I am strong in the faith that I shall live to see home again; it may be otherwise:
I want to be resigned.
But on your account, and also my children`'s,
I have a choice to stay a little longer with you.

After I left Philadelphia, I was at Wrightstown on fourth-day, next at Middletown;
and sixth-day at the Falls; where my esteemed companion John Brown lives;
and he had a minute to travel with me to this yearly meeting.
Seventh-day, attended their select meeting,
and in the afternoon went on to Benjamin Clark`'s, at Stony Brook;
was at their meeting on first-day; second, rode to Rahway;
and next day reached New York +++[+++fifth mo.
10th]; where notice was given of a stranger to be at their week-day meeting.
Word was sent to Long Island, and eight meetings were laid out there, which we attended.

In passing from Matinicock to Bethpage,
we had to ride through Jericho to a small meeting on second-day; lodged there that night,
where a friend of great account had died, and was to be buried on third-day.
We attended the burial, where was a great number of people.
It was strange to me to see the corpse brought into the meetinghouse.

Here I could but admire, as well as at other places, since I found my Beloved,
that I had so much of the tongue of the learned,
in describing the gradual steps of a Christian on his way to heaven,
in a moving deliberate way, without rashness, in the littleness and simplicity.
I am afraid of thinking myself of use among my brethren.
It is enough for me to know most certainly, that He whom my soul loves is with me;
and promises to be with me to the end, in the path I do know I am now in.
I am often afraid, on finding myself much spent, both in body and mind,
lest my Beloved is about hiding himself from me again.
I am also often surprised, in seeing the people show more respect to me,
than others of greater account in society.
Such caresses are trifling to me,
when I remember the bitterness of the wormwood and the gall;
of which I had a large draft, before and since I left home.

I remember your asking me at several times about my expectation of returning home.
I do not remember of giving you much of an answer;
neither can I at this time;--but I have reason to believe,
far from the time of your expectation.
When I write to you again, it is likely it will be from New Bedford, Massachusetts;
and I should be glad to find a letter there from you.

I have thought that there are few, if any fathers,
who have more love and tender affection for a wife and children, than I feel for you;
and yet cannot count it a hardship to travel on, let the path be ever so rough,
when I see the way so clear before me,
even if I do not return home before the next winter.

My love to you is deep and sincere.
Also to my dear children, all equally beloved of their ancient father,

Abel Thomas.

From Providence, under date of tenth month 1st, 1813,
he wrote to the Friends in Philadelphia with whom he stayed when in that city:

Beloved Friends,--

I am at this time at Providence, Rhode Island, in good health,
and have so been since I left your house.
I may inform you, that I have had a prosperous journey so far,
and have laboured through almost all the meetings belonging to this Yearly meeting.
In a few days I shall travel towards New York state, taking in my way,
Pomfret and Kenford, towards New Milford and Oblong; then,
taking the meetings of Friends on to Danby and Ferrisburg, and return back to Granville,
Queensbury, and down the west side of the river to Marlborouofh,--the meetings thereaway,
to Cornwall and New Windsor; then cross the river to New York,
and so return home to my family.

Although I have had a prosperous journey, it has been a rough one;
under which I have been almost ready to faint;
but He whom my soul loved more than all here below, did interfere,
and make hard things easy, and bitter things sweet;
because he did know that I was doing all I could to please him.
I do feel myself satisfied,
and richly paid for all the little services he has required of me.
It is not very likely I have accomplished more than half
the visit set before me a year ago from last spring.
I let no one know, not even my wife, the extent of my visit, until I was, as it were,
raised from the dead, in your city; when my Master let me know that he would go with me;
which promise he has fulfilled to this day, which is great consolation to me,
insomuch that I feel no desire nor inclination for home, to see my wife and children.
I have so far followed the path that was pointed out to me, more than one year past,
without erring, to my knowledge, either to the right hand or to the left.
I do see the path as clearly opened before me, as in the beginning,
and it is my greatest pleasure to walk in it,
without being any way disturbed at what might befall this body in a cold freezing winter.
My friends, wherever my lot is cast, both young and old,
show a great deal of respect for me.

From what is above written concerning my wife and children,
do not judge that I esteem them lightly.
I cannot judge that there is any husband among men,
that has a more near and dear affection for a woman, than I feel for her and my children.
But this I will mention from certain knowledge,
that I love my Master more than wife or children, house or land,
or any created thing in this lower world.
When he is pleased to hide his face from me, for the increase of my love to him,
my wife and children are of little account to me, neither all the world,
nor the glories and pleasures thereof.

My esteemed friend Moses Brown, and his son-in-law,
have purchased a new and convenient carriage for me to ride in,
to take it home to be my own, wherein I can shut myself up from the rain and snow.
The little horse well harnessed, is very tractable in it.
I find it easier for him than carrying me on his back, and much more so for me;
a four wheel carriage not being easily overset.
It is a new invention, not long in fashion: I never saw the like in our country.

I do desire one of you to write to my wife,
and let her know I intend to write to her when I come to Hudson, on the North river.
It may be four weeks first.
I do expect that my wife will be at the Yearly meeting at Baltimore;
and if this comes to your hand in time,
(as likely it will) send it by some friend of your city attending that meeting.
If not, direct it to William Riley, where she makes her home.
I may say in sincerity, I am united in love to you and your children,
more than I can find words to express--I often feel you near to my heart.

And dear friend T. one thing more I desire you to oblige me in; and that is,
if any of my people inquire where I am,
and what I am about so long from home,--tell them, that the old pedlar is moving about,
all weathers, from house to house, and from one meeting to another;
frequently offering his goods at public sale.
And although he had a very small pack when he left home, it was so unaccountably heavy,
that he could not walk straight under it; but thus far, as he has continued faithful,
he has parted with a great quantity of goods.
And also it must appear admirable,
that he cannot perceive his pack is in the least diminished,
but considerably more goods in it;
so that he judges that he has as good an assortment of goods,
as almost any in his occupation, and although not so flashy, yet proved to wear as well.
Whether it is the profit from the sale of his goods, or whether he has grown stronger,
he must leave: however, his pack being much larger and fuller of goods,
he says he can carry it along with ease, and walk straight up, without groaning,
or being in the least weary.
And as the old pedlar does know most certainly that the goods are not his own,
but a living profit is allowed him in the sale thereof,
he is anxious to make what he can to himself.
But the poor pedlar is much disappointed in the sale of his goods,
for his Master will not allow him to carry the key of his pack.
When he comes to the market among his customers,
he must there wait in stillness until his Master gives him the key;
and he sometimes stays long, and sometimes comes not at all.
The poor pedlar is then low, seeing his customers out of patience,
laying all the disappointment on him, and saying, "`Why did he call us here to buy,
and not offer his goods for sale?`"
Truly, from the reasonings of man, it is provoking;--but the poor pedlar cannot help it,
he is so little, so unlearned, and so ignorant,
that it is not worth his while to attempt to make a temporary key,
that he might open his pack when he is pleased.
But I did not understand the pedlar was in any way likely to murmur,
or to be uneasy that he had undertaken so long a journey, for I heard him say,
in a solid frame of mind, that his yoke was easy and his burden light;
and in strict obedience to his Master`'s pointings, he never was happier in his life,
nor more clearly and distinctly understanding his voice.

My dear friends, it seems as if I have been and am in conversation with you,
in a good deal of love and freedom, so that I hardly know how to close.
The old pedlar has found out the reason that his little pack was
so unaccountably heavy that he could hardly live under it,
which is this: his Master told him a year ago from last spring,
that he should make ready to go out on a long journey, peddling;
and there has never been one tittle of his views diminished, or added to.
He wanted to know whether or not he might take the Jerseys last winter,
which he found freedom to do; and in his return from that journey,
he found he had made considerable profit to himself,
from the sale of the goods he dealt away.
When he came home he was easy,
and so happy that he was once more at home with his little family,
they were so near to him, that he did not know how to leave them again,
and more so his wife, to whom he was so nearly united.
When the Lord`'s hand was most heavy upon him, he wanted to be excused,
and he soon fell into a train of reasoning; by and from which, his Master was offended,
and as it were, spoke to him in a stern language, "`Make ready your pack, and go on.`"
And so it was admirable to me;--my endeared wife,
whom I did love more than all in this world, soon became withered in my view,
so that I saw little more comeliness in her,
than in another woman--and now the poor pedlar`'s trouble began.
He thought he had offended his Master, so that he hid his face from him,
and he could find him nowhere; yet he could see the way clear,
which he had marked out for him to walk in, with a woe sounded in his ear.
Frequently the poor pedlar was almost distracted;
he had to bring his case before the judges for some encouragement,
but there were so many ifs and ands that they would not
express unity without some additions of human strength,
according to custom.
Here the poor, weak pedlar added greatly to the weight of his little pack,
in offering to speak in his own defense, which he should not have done;
he ought to have left it to his Master, without meddling.
Although he did know, all the time,
that it was his Master`'s will that he should go on this great visit,
and that self was the cause of the poor pedlar`'s little pack being so very heavy.

I don`'t know whether this writing can be read properly, there are so many misses in it.
I could have added much more concerning the kind entertainment I had in your family,
nearly united to me in love, and my walking as under your vine to meeting,
among the crowd, many of whom I hardly conceive I shall see any more.

I must conclude with a great deal of love; tell your smart little boy,
that the old friend is yet travelling about, and has not since been at home;
that he remembers his love to him, and wishes him to be a good boy.

Abel Thomas.

Thus, with small intermissions,
he was assiduously labouring to promote the cause of his Divine Master,
in turning the minds of his fellow men from darkness to light,
and from the power of Satan unto God;
which honourable service continued to be as his food and drink,
until a short time before his decease.
A few months previous to which, having been, as was often his practice,
looking over his past life, sensible of the infirmities which attended him, he said,
"`I am near eternity: my own nothingness is before me everyday,
on remembering my unworthiness;`" yet he was steadfast in the faith,
and enabled to express himself with clearness respecting
the true and only path to Christian perfection.

At one time he said, "`That wisdom and knowledge which I have gained,
is from striving to follow Jesus Christ in the regeneration;
this is foolishness unto the children of this world, who are pleasing themselves,
or striving so to do, with the perishing enjoyments of this present world.`"
Again--"`I was always seen at our meetings for worship and discipline when at home,
and was silent in those for discipline, being of little account, except in secret prayer,
that the Father of mercies might be our preserver in the meekness of wisdom.
To be a pattern of sobriety and humility among men,
was a lesson which my Master gave me to learn,
and I found it hard and mortifying to experience a growth therein,
notwithstanding my education and low degree in the world was favourable thereto.`"

On recurring again to the subject of meetings for discipline,
under a weighty sense of the temptations and snares which
the enemy of all righteousness presents to the active,
busy spirit of the natural man,
prompting him to attempt the performance of that which can
only be truly done through the spirit of Christ,
the blessed head of the church;
in allusion to such subtle suggestions made at times to his own mind,
he signifies that "`it would seem I had not much more to do than
to learn to be active in treating with others who had not arrived
to such a growth in orderly walking as I had.
Here is a rock, against which many of my fellow-members have been dashed,
and been broken to shivers.
This is a subtle delusion of the transformed angel of light,
which in a considerable degree has put a stop to
their gradual growth in the knowledge of Jesus Christ,
a measure of whose fulness, strictly enjoyed in the inner man, breathes peace, love,
and good will to the fallen children of men.`"

Again, "`Ever blessed Father of mercies, in and through your Son Jesus Christ,
whom my soul loves,
I entreat you to keep me in that love with which you have loved me from my youth up.
Satan had wounded and robbed me; I had lost sight of my Beloved;
but remembering that you are merciful, and would, for the cries of the poor,
arise in your tender compassion, I became acquainted with you through your dear Son,
Jesus Christ; hence I love you more than all these fading, perishing enjoyments.
I cannot describe the thankfulness and humble adoration
which I feel in giving thanks to your great name,
with your dear Son Jesus Christ.
Preserve me from offending you, either in thought, word, or deed.
No tongue can express to the full, nor the most ready writer`'s pen describe,
what you have taught me in the great deeps: that you,
who are King of kings and Lord of lords,
should take notice of your afflicted children who call upon you in the depths of distress,
when none in all the earth can give relief.`"

Again, "`I am now looking towards a vast eternity near at hand, where I hope to rest,
although my pain is great at times, both day and night.
On an inquiry concerning my past long life, tracing my steps, I do comfortably find,
that I have fought a good fight, and have kept the faith.
I feel comfortable in being favoured with ability from all the powers of love in me,
to ascribe high praises to a merciful God, through his Son Jesus Christ.
I am often dejected through fear of offending him whom my soul loves,
and when I can feel him near, I can be as cheerful as a child, in a watchful state.`"

Although his infirmities increased, with great pain,
yet he was preserved in much patience and resignation, and towards the last,
would often say,
that in a little while he should land on that shore where he would have trouble no more.
He departed this life at Monallen, the 21st of Third month, 1816,
in the seventy-ninth year of his age.
